### ISSUE TITLE
Not working on IE Browser

### ISSUE THREAD

**Issue by dghag** [futurepress/epub.js#50]
ePub Reader is not supported to Internet Explorer. I am currently using IE 8.

Webpage error details on IE:

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET4.0C; .NET4.0E)
Timestamp: Mon, 23 Sep 2013 07:29:40 UTC

Message: Object doesn't support this property or method
Line: 874
Char: 42
Code: 0
URI: http://......//js/epub.min.js

**Comment by tehdiplomat** [comment]
I'm on Windows 7 + IE 11, and the reader doesn't work on your own demo site (http://futurepress.github.io/epub.js/reader/) let alone working on my own server. The title bar is visible, and I can click on the different buttons in the title area, but there's no text in the actual iframe area like I see in other browsers.

**Comment by rmunsky** [comment]
Hi,

i have seen several issues for the problem reading epubs on IE. We are having the same problem with some readers asking for IE support. 

Since i have seen several answers to the problem. But it looks like none of them finally worked properly? Is that correct or do i miss something? It would be great if someone could give me some more details of the current state and how to fix that problem.

Does anyone know any other solutions? Ore is there any other alternative rendering epubs in the browser? I like the epub.js solution and would love to keep it, but IE incompatibility is also a problem.

Thanks for any answers or current state notes,

Robert

**Comment by fchasen** [comment]
Apologizes that IE testing in the examples hasn't been a priority, I'll make sure to include it IE 10 and up in my checks going forward. 

Recently we removed the wgxpath requirement for IE and that seems to have added to the confusion.
I'll check what is broken in the reader and update here.

**Comment by MarkisLt** [comment]
IE PERMISSION DENIED [SOLVED]
----
Finaly i've found a solution.
in hooks.js
there is event : renderer:chapterUnloaded, this causes a problem in IE.
FIX:

hooks.js file:
renderer.on("renderer:chapterUnloaded", function(){
try {
item.removeEventListener('load', size);
} catch(e) {
//console.log(e);
}
renderer.off("renderer:resized", size);
});

**Comment by fchasen** [comment]
@rmunsky could you try pulling the latest master and seeing if it solves the issues you were seeing on IE?

**Comment by fchasen** [comment]
I think these issues are all resolved in the 0.2.11 release: https://github.com/futurepress/epub.js/releases/tag/v0.2.11

**Comment by georgezouq** [comment]
@fchasen I try v0.2.15 in IE 10, but it still not work. 
![78930b5fc27f1616e3ac40a7baf0289a](https://cloud.githubusercontent.com/assets/5990860/25064011/d088262a-2223-11e7-9535-afe735a279fe.jpg)
